apiVersion: v1
kind: Secret
metadata:
  name: dhi-registry-credentials
  annotations:
    tekton.dev/docker-0: https://dhi.io
type: kubernetes.io/basic-auth
stringData:
  username: <username> 
  password: <password>
