apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: rust-http-build-
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[refs/heads/main]"
spec:
  
  description: | 
    This pipeline clones a git repo and builds a Docker image
  
  params:
  - name: git-url
    value: "{{ repo_url }}"
  - name: git-revision
    value: "{{ revision }}"
  - name: full-image-name
    value: image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/rust-http:{{ revision }}

  workspaces:
  - name: shared-workspace
  
  tasks:
  - name: fetch-repository
    taskRef:
      resolver: cluster
      params:
      - name: kind
        value: task
      - name: name
        value: git-clone
      - name: namespace
        value: openshift-pipelines
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: URL
      value: $(params.git-url)
    - name: SUBDIRECTORY
      value: ""
    - name: DELETE_EXISTING
      value: "true"
    - name: REVISION
      value: $(params.git-revision)

  - name: rust-build
    taskRef:
      name: rust
    runAfter:
    - fetch-repository
    workspaces:
    - name: source
      workspace: shared-workspace

  - name: build-image
    taskRef:
      resolver: cluster
      params:
      - name: kind
        value: task
      - name: name
        value: buildah
      - name: namespace
        value: openshift-pipelines
    workspaces:
    - name: source
      workspace: shared-workspace
    params:
    - name: IMAGE
      value: $(params.full-image-name)
    runAfter:
    - rust-build
